---

- name: Check http status from user side
  ansible.builtin.uri:
    url: "http://{{ http_test_web_server }}"
    return_content: true
  register: web_contents

- name: Assert that the web site is reachable
  block:
    - name: Assert that Platform Pete is in returned content
      ansible.builtin.assert:
        that: "'Platform Pete' in {{ web_contents['content'] }}"
  rescue:
    - name: Handle service failure gracefully
      ansible.builtin.debug:
        msg: "Platform Pete Industries web service is unavailable"
