---

- name: Test memory
  arista.eos.eos_facts:
    gather_subset:
      - hardware
  register: hw_result

- name: Assert Free Memory
  ansible.builtin.debug:
    msg: "{{ hw_result.ansible_facts.ansible_net_memfree_mb }}"
