---
- name: Test interfaces for Arista switches
  gather_facts: false
  hosts: "{{ dut | default('eda-sw100') }}"

  tasks:
    - name: Test interfaces statuses
      ansible.builtin.include_role:
        name: test_interfaces
      vars:
        messages_kafka_hostname: fedora01.lab.local
        message_kafka_port: 9092
        messages_kafka_topic: arista-topic
      tags: interfaces
#
#    - name: Test BGP Neighbors
#
#    - name: Test external services
