---
- name: Test system settings for Arista Switches
  gather_facts: false
  hosts: eda-sw100
  vars:
    test_name: "arista_test"
    device_name: "eda"
    test_status: "passed"
    # test_name:
    #   - arista_test_interfaces
    #   - arista_test_routing
    #   - arista_test_http

  tasks:
    - name: Assert Free Memory
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', './templates/success_data.j2') }}"
      # loop: "{{ test_name }}"
