---
- name: Test interfaces for Arista switches
  gather_facts: false
  hosts: "{{ dut | default('eda-sw100') }}"
  vars:
    status: "connected"
    enabled: true
    messages_kafka_hostname: fedora01.lab.local
    messages_kafka_topic: ansible-topic

  tasks:
    - name: send to kafka bus
      bob_private_collection.kafka_python.producer_kafkapy:
        host: "{{ messages_kafka_hostname }}"
        port: "{{ messages_kafka_port | default('9092') }}"
        verify_mode: "{{ messages_kafka_verify | default(false) }}"
        topic: "{{ messages_kafka_topic }}"
        data: {
          "status": status,
          "enabled": enabled
         }
